project:
  type: book

book:
  title: "Quarto for Report Makers"
  author: "OceaniaR Hackathon"
  description: "If you are doing an operation more than 3 times it should be a function. The same goes for generating regular or automated reports. Quarto is a powerful tool that allows you integrate your code, text an figures in a single file in order to make high quality, reproducible reports. This is particularly powerful for generating parameterised templates which can generate a report across a number of parameters"
  date: "23/11/2025"
  chapters:
    - index.qmd
    - business-case.qmd
    - output-options.qmd
    - word-quirks.qmd
    - flextables.qmd
    - get-value.qmd
    - interpreting-values.qmd
  appendices:
    - quarto-resources.qmd

format:
  html:
    theme:
      - cosmo
      - brand

execute:
  freeze: auto

editor: visual
